version: '3'
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3300:3000'
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: amir
      DB_PASSWORD: Am13Ir79@@Am13Ir79
      DB_NAME: idehaDB
      JWT_SECRET: w&bQ!^ejJGt98N$z^M
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    ports:
      - '3336:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: idehaDB
      MYSQL_USER: amir
      MYSQL_PASSWORD: Am13Ir79@@Am13Ir79
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
